version: "3.8"
services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/todolist
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    volumes:
      - .:/app
    restart: always
    networks:
      - to-do-list-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
    networks:
      - to-do-list-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - to-do-list-network

networks:
  to-do-list-network:
    driver: bridge